apiVersion: apps/v1
kind: Deployment
metadata:
  name: coms-6156-kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squad-pipeline
  template:
    metadata:
      labels:
        app: squad-pipeline
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - n1-standard-4-node-pool  
      containers:
      - name: squad-pipeline-container
        image: coms-6156-kubeflow/squad-image:latest  
        ports:
        - containerPort: 80  
        resources:
          requests:
            cpu: "4"  
            memory: "15Gi"  
            nvidia.com/gpu: "4"  
          limits:
            cpu: "4"
            memory: "15Gi"
            nvidia.com/gpu: "4"
        env:
          - name: coms-6156-kubeflow  
            value: "squad_training_pipeline"
        volumeMounts:
          - name: squad-volume
            mountPath: /data  
      volumes:
        - name: squad-volume
          persistentVolumeClaim:
            claimName: squad-pvc  
