name: MLOps Pipeline Execution

on: 
  push:
    branches: 
      - main
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kfp
        
    - name: Compile and deploy Kubeflow Pipeline
      run: |
        python src/kubeflow_pipelines/pipeline_definition.py