name: ImageNet Pipeline Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python -m unittest discover -s tests

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: coms-6156-kubeflow/imagenet:latest

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials kubeflow --zone my-zone --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Update Kubeflow Pipeline Deployment
      run: |
        kubectl set image deployment/coms-6156-kubeflow mycontainer=coms-6156-kubeflow/imagenet:latest --record

    - name: Trigger Kubeflow Pipeline
      run: |
        python -m pip install kfp
        python -c "import kfp; client = kfp.Client(host='https://kubeflow.endpoints.coms-6156-kubeflow.cloud.goog/'); client.create_run_from_pipeline_func(pipeline_function, arguments={})"

    - name: Compile and Deploy Kubeflow Pipeline
      run: |
        python src/kubeflow_pipelines/pipelines/imagenet_pipeline.py
